 insert into TEAM (NAME,CURRENCY) values ('liverpool','USD');

insert into PLAYER (TEAM_ID,CONTRACT_ID,NAME,AGE,SALARY,EXPERIENCE_YEAR)
 values (1,1,'john',20,1000000,3);



 insert into CONTRACT (PLAYER_ID,TEAM_NAME,TRANSFER_DATE,RELEASE_DATE,TRANSFER_COST,CONTRACT_COST,TEAM_COMISSION,IS_ACTIVE)
 values (1,'liverpool',PARSEDATETIME('12:22', 'HH:mm'),PARSEDATETIME('12:22', 'HH:mm'),100.00,100.00,100.00,'true');